flywayVersion: 11.17.2
enterpriseUrl: https://download.red-gate.com/maven/release/com/redgate/flyway
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols: { hellip: ... , mdash: --- , ndash: -- , laquo: "<<" , raquo: ">>" , laquo_space: "<< " , raquo_space: " >>" }